edgexfoundry/app-service-configurable

Jenkinsfile

Changes the branch name from "origin/master" to "master" to fix the issue of docker tags not allowing the "/" character
SEMVER_BRANCH variable is set in edgeXSetupEnvironment()
https://github.com/edgexfoundry/edgex-global-pipelines/blob/master/vars/edgeXSetupEnvironment.groovy#L31
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>

Fix branch docker tag to push to Nexus staging

---

go.mod

When running app-service-configurable or any service as a snap service changing the command line options is not possible. Thus the need to add an environment override for specifying the profile.
closes #22

feat(profile): Add environment override for profile command line argument

---

res/configuration.toml
res/docker-blackbox-tests/configuration.toml
res/docker-push-to-core/configuration.toml
res/push-to-core/configuration.toml

Add PushToCore function to pipeline configuration in full sample configs.
Add new `push-to-core` profile that is tailored for HTTP trigger ingestion.
Completes https://github.com/edgexfoundry/app-functions-sdk-go/issues/200

feat(PushToCore): Add PushToCore function to pipeline configurations

---

snap/README.md
snap/hooks/configure
snap/hooks/install
snap/local/runtime-helpers/bin/service-wrapper.sh
snap/snapcraft.yaml

This PR adds snap packaging to app-service-configurable which when built with snapcraft produces a  binary snap named 'edgex-app-service-configurable'.
This snap originally created and published by me, but I've now requested that the name be transferred to EdgeX Foundry. It's been tested by multiple people, and in fact was used by some of the teams at the recent EdgeX Hackathon.
Test instructions can be found in the README.md that's included in this PR.

Add snap packaging

---

Dockerfile
README.md
res/sample/configuration.toml

Move default configuration to `sample` profile so there isn't a default configuration forcing user to specify a profile.
Update the README to document the provided profiles.
closes #36

doc(profile): Move default configuration to "sample" profile

---

README.md

Signed-off-by: davidr@beechwoods.com <davidr@beechwoods.com>

Corrected the mqtt-export related environment variable overrides in README (again).

---

res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/sample/configuration.toml

Mongo authentication is enabled by default.
That is why all micro-services need  to authenticate when trying to connect mongo
Fix: https://github.com/edgexfoundry/app-service-configurable/issues/50
Signed-off-by: difince <dianaa@vmware.com>

Always provide mongo credentials

---

Attribution.txt
go.mod
res/sample-mqtt-msg-bus/configuration.toml

Updated to use latest go-mode-messaging and created the new sample-mqtt-msg-bus profile that configures the MessageBus to use MQTT broker.

feat(MessageBus): Update to lasted go-mod-messaging and create sample profile for MQTT Message Bus

---

go.mod
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/sample-mqtt-msg-bus/configuration.toml
res/sample/configuration.toml

closes https://github.com/edgexfoundry/app-functions-sdk-go/issues/315
Updated to use latest SDK with fix to not initialize secret client if configuration not set.
Also, updated SecretStore config for recent additions.

fix: SecretStore configuration is optional

---

go.mod
main.go

* Upgrades app-functions-sdk-go to use v1.2.0 tag in go.mod
* Cleaned up SDK initialization logging error code (logging client is always initialized before reaching this code)

feat: upgrade to app-functions-sdk-go v1.2.0

---

go.mod
res/blackbox-tests/configuration.toml
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/push-to-core/configuration.toml
res/rules-engine-mqtt/configuration.toml
res/rules-engine-redis/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

Signed-off-by: charles-knox-intel <44684517+charles-knox-intel@users.noreply.github.com>
All profiles in this repository currently only listen on `0.0.0.0`. The `app-functions-sdk-go` dependency does not currently provide a means of configuring this.
Issue Number: #93
The `ServerBindAddr` service configuration option has been added in `app-functions-sdk-go` (https://github.com/edgexfoundry/app-functions-sdk-go/pull/406) as well as `go-mod-bootstrap` (https://github.com/edgexfoundry/go-mod-bootstrap/pull/84). As requested in #93, the configuration option has been added to all services in this repository as well.
No
This change relies on …

feat: set ServerBindAddr config item, fixes #93

---

go.mod
res/blackbox-tests/configuration.toml
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/push-to-core/configuration.toml
res/rules-engine-mqtt/configuration.toml
res/rules-engine-redis/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

Signed-off-by: charles-knox-intel <44684517+charles-knox-intel@users.noreply.github.com>
Currently the dependency version in `go.mod` is out of date and doesn't include the latest fix from https://github.com/edgexfoundry/app-functions-sdk-go/pull/409. Additionally, the sample `configuration.toml` files need to be updated to properly document the fixed behaviors from that PR.
Issue Number: #95 
Dependency updated, and comments updated
Just an updated version for `app-functions-sdk-go`
No

fix: app-functions-sdk-go backwards compatibility, fixes #95

---

go.mod
res/blackbox-tests/configuration.toml
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/sample/configuration.toml

Issue Number: #111
AddTags function is now in the sample, http-export & mqtt-export profiles as well as the blackbox-tests profile
no

feat: Add AddTags function to sample, http-export & mqtt-export profiles

---

Dockerfile
Dockerfile.build
Jenkinsfile
bin/test-attribution-txt.sh
go.mod
snap/snapcraft.yaml

Issue Number: #106
No uses Go 1.15
no

build: Switch to using Go 1.15

---

go.mod
res/rules-engine-redis/configuration.toml

rules-engine-redis profile only works in non-secure mode. Secure mode doesn't work because the random Redis password is required for the connected.
Issue Number: #126
rules-engine-redis profile works in secure and non-secure modes
no

fix: Enable using redis streams MessageBus in secure mode

---

snap/README.md
snap/local/runtime-helpers/bin/startup-env-var.sh
snap/snapcraft.yaml

The module go-mod-bootstrap implements a service dependency check on startup which ensures that all of the runtime dependencies of a particular service are met before the service transitions to active state. With snap deployment, the default values should be sufficient for all of the services as the snap relies on systemd after/before statements to order the bringup of the services. 
To change the startup duration and/interval value of the service, you will need to modify the relevant configuration toml file.
Issue Number:
To change the default startup duration use:
sudo snap set edgex-app-service-configurable startup-duration=
To change the default startup interval use:
sudo snap set …

feat(snap): added startup and duration interval values

---

res/blackbox-tests/configuration.toml
res/mqtt-export/configuration.toml
res/sample/configuration.toml

Deprecated MQTTSend still in profiles and used for MQTT Export.
Issue Number: #108
Replace it with using MQTTSecretSend
no

refactor: Remove use of deprecated MQTTSend

---

res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/rules-engine-redis/configuration.toml
res/sample/configuration.toml

The default mode of Vault now uses http not https,
hence the default value of configuration for Secret Store sections
have been updated to use http and adapted to default values of non-TLS mode.
Closes: #154
- [X ] Feature
Currently the secret store default value from toml file is using tls mode.
Issue Number: #154 
the default value of secret store from toml file changes to non-tls mode
- [X ] No

feat(config): Update configuration files to set default non-TLS

---

res/blackbox-tests/configuration.toml
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/sample/configuration.toml

Now that `Addressable` was removed only the `Parameters` map remains which will not populate in Consul unless there is at least one parameter in the configuration functions configuration. 
Issue Number: #161
Added the dummy `NoOp` parameter configuration for each pipeline function that has no parameters to resolve this issue.
no

fix: All pipeline functions require 1 or more parameters in configuration

---

Dockerfile

The dumb-init utility is required for using security-bootstrapper to gate the secure ASC container startup.
Fixes: #167
Issue Number: #167 
- [x ] No

feat(security): Add dumb-init to Dockerfile of ASC

---

snap/README.md
snap/local/runtime-helpers/bin/security-secret-store-env-var.sh
snap/snapcraft.yaml

This fix adds a new snap configure option 'security-secret-store'
that controls how secrets are stored. By default if a profile's
configuration file requires secrets, secret-store will be used.
If 'security-secret-store' is set to 'false', then insecure
secrets will be used instead. This aligns the snap with the same
capabilty available in the main edgexfoundry snap and the standard
docker-compose files.
Fixes: 150
Signed-off-by: Tony Espy <espy@canonical.com>
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
Issue Number: 150
Secret store usage can now be disabled via a snap config option.
NA
See …

fix(snap): allow disabling of secret-store via config hook

---

Attribution.txt
go.mod
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/rules-engine-mqtt/configuration.toml
res/rules-engine-redis/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

Using SDK that only supports V1 Event Model
All profiles that use MessageBus subscribe to `events` topic only.
Issue Number: #174
Updated to latest SDK that supports V2 Event DTO
All profiles using ZMQ for MessageBus have `edgex/events` added to existing `SubscribeTopics`.
All profiles using MQTT for MessageBus have `edgex/events/#` added to existing `SubscribeTopics`.
no

feat: Update profiles for new subsribe topic for V2 DTOs

---

snap/README.md

The snap's `README` incorrectly stated that security-secret-store could be set to `false` to disable secret store usage. The correct value is `off`.
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
NA
Issue Number: NA
NA
No
No

fix(snap): fix README's security-secret-store doc

---

go.mod
main.go
res/functional-tests/configuration.toml
res/rules-engine-mqtt/configuration.toml
res/rules-engine-redis/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

Uses previous non-refactored SDK
Issue Number: #213
Uses previous refactored SDK
Profiles updated for rename of  `SetOutputData` to `SetResponseData`
BREAKING CHANGE: Pipeline configuration has changed. `SetOutputData` renamed to `SetResponseData`
no

refactor: Rework code and profiles for refactored SDK

---

go.mod
res/functional-tests/configuration.toml
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/push-to-core/configuration.toml
res/rules-engine-mqtt/configuration.toml
res/rules-engine-redis/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

Dependent on https://github.com/edgexfoundry/app-functions-sdk-go/pull/747 to be merged first.
Clients configuration in profiles use old names for services.
Issue Number: #212
Clients configuration in profiles now use the standard service keys for the names for the services.
BREAKING CHANGE: Clients configuration has changed

refactor: Updated profiles to use service keys for Client names

---

go.mod
res/functional-tests/configuration.toml
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/push-to-core/configuration.toml
res/rules-engine-mqtt/configuration.toml
res/rules-engine-redis/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

No support for Registry/Config Access token
Issue Number: #222
Registry/Config Access token now supported.
no

feat: Enable Registry and Config Access Token

---

go.mod
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/rules-engine-redis/configuration.toml
res/sample/configuration.toml

`rules-engine-redis`  profile is missing the Database config section which is needed when Redis is used as the secure message bus
Issue Number: #232 
`rules-engine-redis` profile is now has the Database config section 
no

fix: Add missing Database config to message-bus-redis profile

---

go.mod
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/rules-engine-mqtt/configuration.toml
res/rules-engine-redis/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

SubsribeTopics in many profiles has `events` which was for V1
Issue Number: #239
SubsribeTopics in  profiles no longer contains `events` which was for V1

refactor: Remove V1 subscribe topic from profiles

---

makefile

As part of the Ireland release it was decided to remove the docker- in the image prefix and -go in the image suffix.

ci: update local docker image names in Makefile

---

makefile

fix: Fix version used in local dev docker image

---

Dockerfile
go.mod
res/functional-tests/configuration.toml
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/push-to-core/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

Dependent on edgexfoundry/go-mod-core-contracts#613
Dependent on edgexfoundry/go-mod-bootstrap#216
Dependent on edgexfoundry/app-functions-sdk-go/pull/838
Service key constants have the edgex- prefix
Issue Number:  #252 & #235
Service key constants no longer have the edgex- prefix
Hyphen in Overrides are converted to underscore
BREAKING CHANGE: Service key names used in configuration have changed.
no

refactor: Update for new service key names and overrides for hyphen to underscore

---

res/functional-tests/configuration.toml
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/push-to-core/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

Ports assigned for Core/Supporting services are 408xx range
App services never had a ranged assigned
Issue Number: #257
Ports assigned for Core/Supporting services are 588xx range
App services now assigned the 597xx range
BREAKING CHANGE: App Service Configurable default port numbers have changed.
no

refactor: Update to assign and use new Port Assignments

---

go.mod
res/functional-tests/configuration.toml
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/push-to-core/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

SecretStore config no longer support Retry related properties and secret path now only needs service specific path, /v1/secret/edgex/ automatically prefix in front of it.
Fixes: #271
- [x ] Refactoring (no functional changes, no api changes)
Retry  related properties exists and secret path is full path.
Issue Number:  #271 
Retry related properties are removed and secret path is just service specific.
- [x ] No
In draft mode until we have tagged app-function-sdk version available for go.mod from CI pipeline.

fix: Remove retry related properties and update secret path of SecretStore config

---

res/http-export/configuration.toml

Http Export has secrets setting populated causing TAF tests to fail
Issue Number: #279
Http Export has secrets setting back to un-set
no

fix: Make default http export secret settings blank as default

---

res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

Some Profiles are missing the additional optional MQTT MessaegBus settings so env overrides do not work when enable MQTT from compose files.
One has incorrect value for Client ID
Issue Number:  #304
All profiles have additional optional MQTT MessaegBus settings allowing env overrides to work properly
Client ID is set properly in all profiles
no

fix: Add/Fix optional MQTT MessageBus settings

---

.github/PULL_REQUEST_TEMPLATE.md

PR template does have section for related Docs PR and has obsolete type section
Issue Number: n/a
PR template now has section for related Docs PR and no longer has obsolete type section
n/a

docs: Add Doc PR section, removed obsolete types section

---

go.mod
go.sum
res/external-mqtt-trigger/configuration.toml
res/functional-tests/configuration.toml
res/http-export/configuration.toml
res/mqtt-export/configuration.toml
res/push-to-core/configuration.toml
res/rules-engine/configuration.toml
res/sample/configuration.toml

All profiles now have the default CORS configuration.
closes #341
Will be handled by @cloudxxx8 via this issue Create document to instruct the CORS settings edgex-docs#608
1. Clone the branch for this PR
2. Clone the branch for SDK PR (https://github.com/edgexfoundry/app-functions-sdk-go/pull/983)
3. Build ASC
4. Run ASC - `./app-service-configurable -p functional-tests -s`
5. Send GET request to `localhost:59705/api/v2/ping`
6. Verify CORS headers not in response
7. …

feat: Add CORS capability

---

snap/snapcraft.yaml

This commit adds "app-functional-tests" to the list of bind mount points set up by the
edgex-secretstore-token slot, so that the secret store token for that profile is available
when running TAF tests.
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
1. build edgex-app-service-configurable_2.0.2-dev.25_amd64.snap 
```
git clone https://github.com/siggiskulason/app-service-configurable.git
cd app-service-configurable
git checkout fix-snap-build
snapcraft --use-lxd
```
2. then install, configure …

feat(snap): add content interface mount point for app-functional-tests secrets token

---

go.mod
go.sum
res/http-export/configuration.toml
res/metrics-influxdb/configuration.toml
res/mqtt-export/configuration.toml
res/sample/configuration.toml

Set MergeOnSend = "true"
Set MergeOnSend = "false" in other profiles that use batch
closes #411
TBD
Build and run App Template service to generate metrics
Build ASC with this branch
Configure ASC metrics-profile with HTTP to send to InfluxDB
Run ASC with metrics-profile with DEBUG logging
Verify HTTP Export reports status is 204 No Content in log file

feat: Used Batch for metrics-influxdb profile

---

README.md
snap/README.md

Usage instructions are being moved to docs; see https://github.com/edgexfoundry/edgex-docs/pull/751.
The snap/README has been updated to include development docs only.
Depends on:
- https://github.com/edgexfoundry/edgex-docs/pull/751
Signed-off-by: Farshid Tavakolizadeh <farshid.tavakolizadeh@canonical.com>

docs(snap): Remove usage instructions from readme

---

makefile

fixes #423
create local `./VERSION` with "v2.2.0" as contents
run `make build`
start non-secure EdgeX Stack
run `./app-service-configurable -p=sample' 
hit `localhost:59700/api/v2/version`
Verify response is:
```
{
"apiVersion": "v2",
"version": "v2.2.0",
"serviceName": "app-sample",
"sdk_version": "v2.2.0"
}
```

fix: Correctly set the App and SDK versions when building the binary

---

.gitignore
snap/local/hooks/go.mod
snap/snapcraft.yaml

Upgrade snap packages left out in #438

build(snap): Upgrade to Go 1.18

---

Dockerfile
go.mod
go.sum
makefile

BREAKING CHANGE: ZeroMQ MessageBus capability no longer available
Build branch locally without gcc and zmq libs available.
Verify sample builds and run as expected.
Run `TRIGGER_EDGEXMESSAGEBUS_TYPE=zero ./app-service-configurable -p=sample`
Verify service fails with `msg="unknown message type 'zero' requested"`

feat!: Remove ZeroMQ MessageBus capability

---

res/sample/configuration.toml

Compress function will eventual panic the service.
- [x ] I am not introducing a new dependency (add notes below if you are)
Run service with sample profile
Verify after 10 mins it does not panic.

refactor: Remove use of Compress function in sample profile due to issues

---

Attribution.txt
snap/snapcraft.yaml

BREAKING CHANGE: ZeroMQ MessageBus capability no longer available

build!: Remove ZMQ from snap

---

makefile

Run non-secure edgex stack from compose builder
```
make run no-secty ds-virtual
```
build service from this branch
Verify it builds properly
run service
```
./app-service-configurable -p sample -cp -d -o
```
Verify service bootstraps successfully and starts process events from the MessageBus

build: [ASC]  Add ldflags to strip debug info from binary

---

go.mod
go.sum
res/db/sql/00-utils.sql
res/db/sql/01-tables.sql

Relates to app-functions-sdk-go/#1603. Add postgres db init start script for app svc schema/table.

feat: Add postgres db init start script

---

README.md
go.mod
go.sum
makefile

related to https://github.com/edgexfoundry/go-mod-bootstrap/pull/795
To allow to build services without openziti, add new targte build-noziti and docker-noziti into Makefile. Also revise README.md to include such information.

feat: Add new build-noziti and docker-noziti targets into Makefile
