- README.md
- go.mod
- res/configuration.toml
- res/docker-http-export/configuration.toml
- res/docker-mqtt-export/configuration.toml
- res/docker/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
Add `MarkAsPushed` to default and export profiles. Export profiles actually uses it in those pipelines. Update README to include using `MarkAsPushed` in example.
Closes #2 
> feat(profiles) : Update configuration profiles to include new MarkAsPushed function

- Jenkinsfile
Signed-off-by: Ernesto Ojeda <ernesto.ojead@intel.com>
> move dockerLogin for required push step

- Jenkinsfile
Signed-off-by: Ernesto Ojeda <ernesto.ojead@intel.com>
> add clair scan stage

- Jenkinsfile
Signed-off-by: Ernesto Ojeda <ernesto.ojead@intel.com>
> fix port for clair scan

- README.md
- go.mod
- makefile
- res/configuration.toml
- res/docker/configuration.toml
Update to latest SDK that implements UseTargetTypeOfByteArray and document how to use it in the Pipeline configuration.
close #9
> feat(TargetType): Document use of UseTargetTypeOfByteArray 

- Jenkinsfile
Signed-off-by: Mike Johanson <michael.johanson@intel.com>
> build(docker): Adding latest and branch tags to docker images for nexus

- res/docker/configuration.toml
closes #15
Signed-off-by: Mike Johanson <michael.johanson@intel.com>
> fix(configuration): There is a duplicate LogLevel key in the TOML

- Dockerfile
- go.mod
- makefile
Also fix make and docker issues
closes #6
> fix(Profile): Use latest SDK with Registry HasConfiguration fix

- .gitignore
- Attribution.txt
- bin/test-attribution-txt.sh
- bin/test-go-mod-tidy.sh
- go.mod
- makefile
Add missing Attribution.txt file, add attribution and go mod tidy tests to `make test`, run tests and fix missing items.
closes #5
> fix(Attribution): Add Attribution.txt file and tests to "make test"

- Jenkinsfile
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
> add snyk stage

- Jenkinsfile
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
> fix edgeXSnyk global var call

- Attribution.txt
- go.mod
- res/configuration.toml
- res/docker-http-export/configuration.toml
- res/docker-mqtt-export/configuration.toml
- res/docker/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
Update appropriate configurations for new settings created for Store and Forward.
closes #111
> feat(StoreForward): Use latest SDK and update configurations for Store & Forward

- res/blackbox-tests/configuration.toml
- res/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/push-to-core/configuration.toml
- res/rules-engine/configuration.toml
As part of fixing issue [#232](https://github.com/edgexfoundry/app-functions-sdk-go/issues/232), the configuration TOML files requires to change.
> feat(configuration): Update configuration intervals in TOML to duration string

- go.mod
> fix(appfunsdk-version) Fix issue #30: Update to the latest app-function-sdk

- res/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
Export and sample configurations updated for Vault integration
closes #34
> bug(StoreForward): Add missing configuration for Vault Integration for DB credentials

- Attribution.txt
- go.mod
> build (SDK): Update to use latest SDK with Vault integration bug fix.

- go.mod
> build (go.mod): Updated to use v1.0.0 of App Functions SDK.

- README.md
#46 
Signed-off-by: kurokobo <2920259+kurokobo@users.noreply.github.com>
> Fix issue #46: Update environment variables in README.md

- .gitignore
- Dockerfile
- Dockerfile.build
- Jenkinsfile
- go.mod
> Update relevant files in app-service-configurable for Go 1.13.

- go.mod
- res/sample/configuration.toml
closes #53 and #55
Signed-off-by: Mike <michael.johanson@intel.com>
> build(go.mod): update sdk version for latetest features

- Attribution.txt
- go.mod
- res/rules-engine-redis/configuration.toml
- res/rules-engine/configuration.toml
- Updated go.mod to use latest go-mod-messaging 
- Added new rules-engine-redis profile configured to use 'redisstreams' for the Message Bus
> feat(Message Bus): Integrate new Redis Message Bus

- Dockerfile
- README.md
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/sample/configuration.toml
Misc tech debt for change in default DB and use of new config provider
> refactor: Change Database to be Redis and add -cp command line to Dockerfile entrypoint

- go.mod
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/sample/configuration.toml
Profiles updated with latest security configuration for [SecretStoreExclusive], [InsecureSecrets} and a few misc function parameters for secrets.
> feat: Updated profiles for latest security config and to latest SDK

- snap/snapcraft.yaml
closes #41
Signed-off-by: Mike <michael.johanson@intel.com>
> fix: incorrect documentation link for snap

- go.mod
- res/blackbox-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/rules-engine-mqtt/configuration.toml
- res/rules-engine-redis/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
feat: Add ability to Filter functions to reverse the logic to filter out specified names
close #<359#>
Signed-off-by: Brian McGinn <brian.mcginn@intel.com>
> feat: Add ability to Filter functions to reverse the logic to filter out specified names

- Jenkinsfile
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
> Update Jenkinsfile to include snap

- .github/semantic.yaml
Signed-off-by: Mike <michael.johanson@intel.com>
> ci: add semantic.yml for commit linting

- snap/snapcraft.yaml
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
> build(snap): Update snapcraft.yaml version (1.2.0)

- .github/PULL_REQUEST_TEMPLATE.md
Added latest PR template which includes `new modules` question.
> docs: Add latest PR template

- .dockerignore
- Dockerfile
Attribution.txt and LICENSE file not in the docker image
Issue Number: app-functions-sdk-go/issues/329
Attribution.txt and LICENSE file are in the docker image
No
> build: Add Attribution.txt and LICENSE file to docker image

- go.mod
- res/blackbox-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/push-to-core/configuration.toml
- res/rules-engine-mqtt/configuration.toml
- res/rules-engine-redis/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
Active client monitoring has been removed so the ClientMonitor setting is no longer needed.
Issue Number: #86
ClientMonitor setting removed from all profiles
Updated to latest SDK with client monitoring removed.
No
> refactor: Remove ClientMonitor setting.

- Attribution.txt
- go.mod
chore: remove mongo DB implementation
close #89
Signed-off-by: Brian McGinn <brian.mcginn@intel.com>
Includes app-functions-sdk with MongoDB support
https://github.com/edgexfoundry/app-service-configurable/issues/89
Issue Number: 89
updates app-functions-sdk that removes support for MongoDB
Changes will break the stack for anyone using MongoDB. To avoid errors the users of app-functions-sdk must convert to redisDB
no
This change will break users of the MongoDB compose files.
> chore: remove mongo DB implementation

- Attribution.txt
- go.mod
Mongo implementation was prematurely removed
Issue Number: #92
Mongo implementation has been restored by updating to latest SDk which has the mongo implementation restored
no
> revert: remove mongo implementation

- go.mod
version check in BB Tests failed due to new `dev` version from Core Data
Issue Number: #100
version check now accepts Core Data's new `dev` versions.
no
> build: Updated to latest SDK with version check fix

- README.md
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
n/a
Issue Number:
none
Added version and LTS links to readme per architect's meeting of Aug 2020
none
none
> docs: addition of verion and LTS references to READMe per arch's meeting

- Attribution.txt
- go.mod
> fix: Update to latest SDK so V2 APIs are available for TAF tests

- go.mod
Issue Number: #115
This version fixes V2 MetricRespone scheme & SecretsRequest requestId now optional
no
> build: Update to latest App SDK

- go.mod
- res/http-export/configuration.toml
- res/sample/configuration.toml
Issue Number:  #128
Http Export using PUT method now available via the HTTPPut pipeline function
no
> feat: Add ability to use PUT method for HTTP Export in configurable pipeline

- go.mod
- res/blackbox-tests/configuration.toml
- res/rules-engine-mqtt/configuration.toml
- res/rules-engine-redis/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
Does not have ability to set custom content type
Issue Number:
#131 
Now it has the ability to set custom content type
no
> feat: Add ResponseContentType to SetOutputData

- .github/dependabot.yml
DependaBot runs weekly
Issue Number: #136
DependaBot runs daily
No
> build: Change DependaBot to run daily

- go.mod
ASC now has content type bug
Issue Number: #139
ASC now has fix for content type
no
> build: Update to used latest SDK with content type fix

- go.mod
- res/blackbox-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/push-to-core/configuration.toml
- res/rules-engine-mqtt/configuration.toml
- res/rules-engine-redis/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
Remote Logging feature has been remove, but profiles still have remote logging config
Issue Number:  #88
Profiles no longer have remote logging config
> feat: Remove remote logging capability

- go.mod
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
Some profiles have MarkAsPushed
Issue Number: #152
No profiles have MarkAsPushed
no
> feat: Remove MarkAsPushed feature

- go.mod
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/rules-engine-mqtt/configuration.toml
- res/rules-engine-redis/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
Profiles use old SubscribeTopic for a single topic
Issue Number: #152
Profiles use new SubscribeTopics allowing for single or multiple topics
No
> feat: Allow for multiple MessageBus subscriptions

- Attribution.txt
- go.mod
- main.go
- makefile
Consumes the SDK as a V1 Go Module
Issue Number: #165 
Consumes the SDK as a V2 Go Module
no
> refactor: Consume new V2 App SDK

- Attribution.txt
- go.mod
On previous version of SDk which doesn't consume all the V2  edgex go-mods.
Issue Number: #169
Updated to use latest SDK which now consumes all the V2 edgex go-mods
Required updating Attribution.txt
no
> build: Consume latest SDK V2 Module

- go.mod
1.3.0 SDK version for Hanoi doesn't contain the ZMQ fix needed for 1.3.1 Release
Issue Number: #173
Latest SDK 1.3.1-dev.1 contains the needed ZMQ fix for the 1.3.1 Release
no
> fix: Upgrade to go-mod-messaging with ZMQ fix for Hanoi

- go.mod
Pre-release version of SDK used.
Issue Number:  #173
Released version (1.3.1) of the SDK is used
no
> build: Update to use released SDK for 1.3.1 dot release

- go.mod
- res/functional-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/rules-engine-mqtt/configuration.toml
- res/rules-engine-redis/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
Profiles contain old name FiliterByValueDescriptor and don't have the new FilterByProfileName.
Issue Number:  #185
Profiles contain new name FiliterByResourceName and now have the new FilterByProfileName.
no
> feat: Update profiles for new filter enhancements

- go.mod
- res/functional-tests/configuration.toml
- res/sample/configuration.toml
Profiles don't have secrets configuration parameters  for EncryptWithAES
Issue Number: #194 
Profiles now have secrets configuration parameters for EncryptWithAES
no
> feat: Added secrets configuration parameters to EncryptWithAES

- Attribution.txt
- go.mod
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/rules-engine-redis/configuration.toml
- res/sample/configuration.toml
- SecretStore configuration doesn't required `Type` field
- bug where DTO validation results in 500 error code, rather than proper 400 code
- bug where dynamic pipeline configuration errors leaving pipeline active which hides the errors
Issue Number:  #191
- SecretStore configuration now have a required `Type` field
- Fix bug so the 400 status code is properly returned for DTO validation error instead of 500
- Fix bug for dynamic pipeline configuration errors leaving pipeline active which hides the errors
BREAKING CHANGE: requires SecretStore.Type be set to `vault`
no
> feat: Update profiles for latest SDK changes

- .gitignore
- go.mod
- res/http-export/configuration.toml
- res/sample/configuration.toml
close 
Unable to override SecretHeader value in InsecureSecrets as the header name is used as the key in the TOML.
Issue Number: #197
Now able to override SecretHeader value in InsecureSecrets as the key in the TOML is not the header name and the key can remain as specified in the ASC profiles allowing it's value to be overridden as with any other values in the TOML.
BREAKING CHANGE: Parameters have changed for HTTP Post/Put with SecretHeader
no
> refactor: Update profiles for refactored http export with secret header

- go.mod
- res/functional-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/push-to-core/configuration.toml
- res/rules-engine-mqtt/configuration.toml
- res/rules-engine-redis/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
Profiles have `[Binding]` section for trigger configuration with related configurations disjoint
Issue Number: #199
Profiles now have `[Trigger]` section for trigger configuration with related configurations as sub-sections
BREAKING CHANGE:
- Renamed `Binding` to `Trigger`
- Removed deprecated `MessageBus` trigger type, replaced by `edgex-messagebus`
- Renamed `MessageBus` to `EdgexMessageBus`
- Move `EdgexMessageBus` and `ExternalMqtt` under Trigger configuration
> refactor: Update profiles for change in Trigger configuration

- go.mod
- res/functional-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/sample/configuration.toml
Profiles have redundant pipeline function configuration that can be consolidated
Issue Number:  #204
Profiles have been update to consolidate pipeline function configuration
BEAKING CHANGE: function pipeline configuration changed
no
> refactor: Consolidate function pipeline configuration

- go.mod
- res/functional-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/rules-engine-mqtt/configuration.toml
- res/rules-engine-redis/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
New FilterBySourceName function not in the profiles
Issue Number: #202
New FilterBySourceName function now in the profiles
no
> feat: Add FilterBySourceName to profiles

- Attribution.txt
- go.mod
gorilla/websocket not in Attribution.txt
Issue Number: #219
Updated to latest SDK
gorilla/websocket now in Attribution.txt
> build: Update to latest SDk and add gorilla/websocket to Attribution.txt

- go.mod
Uses 1.0 consul path
Issue Number: #221
Now uses 2.0 consul path
BREAKING CHANGE: Consul configuration now under the /2.0/ path
> refactor: Switch to 2.0 Consul path

- go.mod
- main.go
- res/functional-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/push-to-core/configuration.toml
- res/rules-engine-mqtt/configuration.toml
- res/rules-engine-redis/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
closes 
BREAKING CHANGE: When run with the secure Edgex Stack now need to have the SecretStore configured, a Vault token created and run with EDGEX_SECURITY_SECRET_STORE=true.
BREAKING CHANGE: Service key changed to `app-<profile name>`
Registry/Config access tokens capability supported via files
Issue Number:  #222
Registry/Config access tokens capability now supported via SecretProvider
Non-standard mixed case service key name change to simplified lower case `app-<profile name>`
Removed previous file based access token config settings
BREAKING CHANGE: When run with the secure Edgex Stack now need to have the SecretStore configured, a …
> feat: Add Registry/Config Access token capability via Secret Provider

- Dockerfile
- Dockerfile.build
- go.mod
- makefile
- snap/snapcraft.yaml
Files specify Go 1.15
Issue Number: #245
Files now specify Go 1.16
no
> ci: Update files for Go 1.16

- go.mod
- res/functional-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/push-to-core/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
closes
Topic config not in logical location
Issue Number:  #248
Topics config now in proper location
> refactor: Move topic config to appropriate config struct

- res/functional-tests/configuration.toml
> fix: Remove duplicate settings in functional-tests profile

- res/mqtt-export/configuration.toml
mqtt-export profile has wrong service port
Issue Number: #269
mqtt-export profile now has correct service port
no
> fix: Update mqtt-export port to proper value of 59703

- go.mod
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/sample/configuration.toml
SDK version used doesn't have capability and profiles don't have new configuration settings
Issue Number: #276
SDK version used has the capability and profiles have new configuration settings
no
> feat: Multiple HTTP export destinations via chaining

- go.mod
- res/push-to-core/configuration.toml
- res/sample/configuration.toml
Profiles setting for PushToCoreData are for V1
Issue Number:  #200
Profiles setting for PushToCoreData are now for V2
- [] No
BREAKING CHANGE: PushToCoreData  configuration has changed
>  feat: Update profiles for V2 PushToCoreData

- go.mod
- res/functional-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/push-to-core/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
Profile only have Core Data client
Issue Number: #290
Latest SDK uses Core Metadata client for start-up version check so profile have been changed to all have Core Metadata client.
Sample profile update to have all supported clients with descriptions
Other profile update to have only clients required by the use case.
BREAKING CHANGE: Core Metadata client now required for version check on startup
no
> feat: Update profiles for newly added/updated clients

- go.mod
> build: Update to latest SDK dev.85

- CHANGELOG.md
No Change Log exists
Issue Number: #904
Change Log now exists and updated for upcoming Ireland release
- [ x No
no
> docs: Add ChangeLog

- go.mod
Using pre-release SDK
Issue Number: N/A
Using v2.0.0 released SDK
> build: Update to use released 2.0.0 SDK

- snap/local/runtime-helpers/bin/startup-env-var.sh
When we forward ported the env config override
support from Hanoi, we missed the code in the
service wrapper which sources the .env file.
Signed-off-by: Tony Espy <espy@canonical.com>
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
Issue Number:
No
> fix(snap): fixup env config overrides

- CHANGELOG.md
- go.mod
Using SDK 2.0.0 which has bugs
Issue Number: n/a
Using SDK 2.0.1 which has bugs fixes
Updated Changelog for 2.0.1 patch release
no
> build: Update to SDK 2.0.1 and update Change Log for patch release

- GOVERNANCE.md
- OWNERS.md
- res/functional-tests/configuration.toml
- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
- res/push-to-core/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
Mix of single quotes and double quotes in TOML Files
Issue Number: n/a
Replaced single quotes with double quotes in TOML Files
Added governance.md and owner.md files for LF Edge
no
> refactor: Clean up TOML quotes and add LF MD files

- snap/README.md
Remove reference to the usage of configuration file content
interfaces to provision new profiles. This was removed from
the Ireland snap due to the change in the way tokens are
generated for specific App Service Configurable profiles.
Signed-off-by: Tony Espy <espy@canonical.com>
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
Issue Number:
No
> fix(snap): update snap/README

- Dockerfile
Related Docs PR:
If n/a for Docs PR, state why it is not applicable:
Issue Number:
> build(docker): update dockerfile to alpine3.14

- Attribution.txt
- go.mod
- go.sum
- main.go
- res/sample/configuration.toml
Related Docs PR: https://github.com/edgexfoundry/edgex-docs/issues/548
ASC not updated for latest enhancement of Pipeline per topics.
Issue Number:  #321
ASC now updated for latest enhancement of Pipeline per topics.
**Add modules are already EdgeX Approved.**
> feat: Update for SDK multi-topics per pipeline

- Dockerfile
Related Docs PR: N/A
If n/a for Docs PR, state why it is not applicable: Just version change to base image
Final base image still using alpine 3.12
Issue Number: n/a
Final base image now using alpine 3.14
> build: Update runtime base image to alpine 3.14

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/semantic.yaml
Update PR Template to the newly approved template 
Added missing Contribution.md
Also updated the semantic.yaml to match topics in Contributing.md
> ci: Update PR template and add missing Contribution.md

- README.md
fixes #350
1. Open README in tool that vendors the mark down
2. Verify the links are not broken and sections can be navigated to as described.
3
N/A
> fix: Updated stale README

- go.mod
- go.sum
> fix: Update to latest SDK for config pipeline bug fixes

- go.mod
- go.sum
**N/A for build PR**
**N/A for build PR**
> build: Update to use released SDK

- go.mod
- go.sum
- res/metrics-influxdb/configuration.toml
Uses ToLineProtocol function and HTTP export of transformed metric to
Influxdb
close https://github.com/edgexfoundry/app-service-configurable/issues/400
TBD
Run profile configured for local InfluxDB
Run rules-engine profile with metrics enabled
Verify InfluxDB is receiving and accepting the metrics.
> feat: Add new metrics-influxdb profile

- CHANGELOG.md
> docs: Update change log for Kamakura release

- res/metrics-influxdb/configuration.toml
> fix: Corrrect typos in comments in new profile

- res/metrics-influxdb/configuration.toml
> fix: Update port number for new metrics-influxdb profile to be 59707

- res/http-export/configuration.toml
- res/mqtt-export/configuration.toml
> fix: Add missing Publish Host config so metrics can be published

- bin/test-attribution-txt.sh
> build: Optimize test-attribution-txt.sh to use go.mod, not vendor

- Dockerfile
- README.md
- makefile
- res/http-export/configuration.toml
- res/metrics-influxdb/configuration.toml
- res/mqtt-export/configuration.toml
- res/rules-engine/configuration.toml
- res/sample/configuration.toml
https://github.com/edgexfoundry/edgex-docs/pull/846
run `make build-nats`
Verify `-tags "include_nats_messaging"` is in the `go build` command
run  `make docker-nats`
Verify `-tags "include_nats_messaging"` is in the `go build` Step for the docker image
> build: add build targets for NATS and add NATS configuration

- res/http-export/configuration.toml
- res/metrics-influxdb/configuration.toml
- res/mqtt-export/configuration.toml
- res/rules-engine/configuration.toml
> fix: Restore ClientId values changed in previous change

- README.md
- makefile
Run the following commands and verify each Go build step includes `-tags "include_nats_messaging ...`
```
make build-nats
make docker-nats
```
> build: Add NATS convenience build targets

- res/sample/configuration.toml
closes: #490
Signed-off-by: Marc-Philippe Fuller <marc-philippe.fuller@intel.com>
`cd edgex-compose/compose-builder`
`make run no-secty ds-virtual`
`cd app-functions-sdk/app-service-template`
`make build`
`./app-service-configurable -p sample  -cp`
Check logs to see if there are any errors
> fix: enable core-command via message bus

- res/sample/configuration.toml
BREAKING CHANGE: use MQTT wild cards + for single level and # for multiple levels
> refactor!: Update message bus topic wild cards

- .golangci.yml
- Dockerfile
- go.mod
- makefile
- snap/local/helper-go/go.mod
- snap/snapcraft.yaml
run non-secure edgex stack with ds-virtual with dev images
build and run ASC from this branch with sample profile
verify service bootstraps and data is flowing from Device Virtual
> build: Update to Go 1.20, Alpine 3.17 and linter v1.51.2

- snap/local/bin/service-wrapper.sh
- snap/snapcraft.yaml
- Inline CLIs flags
- Remove unused packages
- Remove external metadata sourcing
- Remove deprecated startup-duration and startup-interval snap options
> refactor(snap): Update command and metadata sourcing

- res/external-mqtt-trigger/configuration.yaml
- res/http-export/configuration.yaml
- res/metrics-influxdb/configuration.yaml
- res/mqtt-export/configuration.yaml
- res/sample/configuration.yaml
closes: #537
1. start up edgex with no-secty, mqtt-broker and ds-virtual
2. `make build app-service-configurable`
3. run `./app-service-configurable -p {profile_name} -cp`
4. verify app service starts up with no error
5. stop app-service-configurable, and uncomment hybrid settings for each profile
6.   run `./app-service-configurable -p {profile_name} -cp -o`
7.  verify app service starts up with no error
> fix: Store and Forward Enabled missing from profiles

- Jenkinsfile
- go.mod
- go.sum
- vendor/github.com/edgexfoundry/app-functions-sdk-go/v2/pkg/transforms/compression.go
- vendor/modules.txt
run make docker
Modify `docker-compose-no-secty-with-app-sample.yml` to use `edgexfoundry/app-service-configurable:0.0.0-dev`
Run modified compose file
from Consul set app-sample logging to DEBUG
from Consul set default pipeline ExecutionOrder to `Compress, SetResponseData`
Let service run for 5 mins and verify no panic.
from Consul Compress function Algorithm to `zlib` 
Let service run for 5 mins and verify no panic.
> fix: [jakarta] Make Compression functions thread safe

- CHANGELOG.md
- go.mod
- go.sum
> build:[Levski] Use released patched SDK and update changelog

- res/sample/configuration.yaml
closes #542
run `make docker`
Modify this [compose file](https://github.com/edgexfoundry/edgex-compose/blob/8a22ffe3ee580c257e50e40c2b53eff48da465fe/docker-compose-no-secty-with-app-sample.yml) by changing ASC images to edgexfoundry/app-service-configurable:0.0.0-dev
run the compose file.
Verify `app-sample` and `app-rules-engine` bootstrap successfully
> fix: Comment out Host overrides in local config file.

- go.mod
- go.sum
> fix: Consume Store and Forward fix in latest SDK

- CHANGELOG.md
- Jenkinsfile
- go.mod
- go.sum
Run EdgeX Secure Stack
Run make docker
From compose builder run `make run ds-virtual app-dev`
Verify common endpoints, except ping, require JWT token
Verify ping endpoint doesn't require JWT token
> build: Update for patch 3.0.1 release

- res/external-mqtt-trigger/configuration.yaml
> fix: Add InsecureSecrets section to external-mqtt-trigger profile

- README.md
Now can point directly to the appropiate sections using `latest` No reason to have link to examples here.
- [x ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
Click link in rendered Readme
Verify it opens the correct section in the EdgeX docs
> docs: Update repo links in the readme

- res/external-mqtt-trigger/configuration.yaml
- res/mqtt-export/configuration.yaml
- res/sample/configuration.yaml
https://github.com/edgexfoundry/edgex-docs/pull/1252
Run non-secure EdgeX stack
Build ASC from this branch
Run the following and verify each bootstraps w/o error
```
./app-service-configurable -cp -d -p external-mqtt-trigger
./app-service-configurable -cp -d -p sample
./app-service-configurable -cp -d -p mqtt-export
```
> feat: Add defaults for new Last Will options

- README.md
Note: Rendored link will be broken until docs 3.1 does are released
> docs: [ASC] Update link to point to new docs section

- CHANGELOG.md
> docs: Update chengelog for release 3.1

- makefile
> build: Fix vendor target

- Attribution.txt
- Dockerfile
- go.mod
- makefile
Upgrade to go-1.23, Linter1.61.0 and Alpine 3.20
- make build
- make test
- make docker
> build: Upgrade to go-1.23, Linter1.61.0 and Alpine 3.20

- makefile
Run the following command to build binary
```
make build
```
Verify that `Full RELRO` and `PIE enabled` are displayed
```
checksec --file=./app-service-configurable
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
Full RELRO      No canary found   NX enabled    PIE enabled     No RPATH   No RUNPATH   59275) Symbols	  No	0		0		./app-service-configurable
```
> feat: Enable PIE support for ASLR and full RELRO

- makefile
> fix: Only one ldflags flag is allowed

- makefile
> build: Upgrade the SDK version in makeile

- .gitignore
- Attribution.txt
> build: update .gitignore and Attributions.txt
